name: "PipManager Continuous Integration"

on:
  push:
     branches:
        - development
    
jobs:
  build:
     runs-on: windows-latest
     env:
        Project_Path: src/PipManager/PipManager.csproj
        Executable_Path: publish/PipManager.exe
     steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
     
        - name: Install .Net 8
          uses: actions/setup-dotnet@v4
          with: 
            dotnet-version: 8.0.x

        - name: Restore
          run: dotnet restore ${{ env.Project_Path }}
  
        - name: Build
          run: dotnet build ${{ env.Project_Path }} -c Release --no-restore
  
        - name: Publish
          run: dotnet publish ${{ env.Project_Path }} -c Release -r win-x64 -o "publish/" -p:Platform=x64 -p:PublishReadyToRun=false -p:EnableCompressionInSingleFile=false -p:PublishSingleFile=true -p:SelfContained=false -p:AssemblyVersion=1.0.0.0
  
        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: PipManager-dev
            path: ${{ env.Executable_Path }}